### ISSUE TITLE
REDIS_MASTER_SET is not set properly in sentinel.conf for version 7.0.0

### ISSUE THREAD

**Issue by jaimem88** [UltimateTournament/ArcadeUnitySDK#4]
Setting `REDIS_MASTER_SET` does not work properly on version 7.0.0. See sample `docker-compose.yml`

```yaml
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_SET=some-other-master
    ports:
      - '26379:26379'
    networks:
      - app-tier
```

Looking at the logs:

```
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.13
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.14 Welcome to the Bitnami redis-sentinel container
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-sentinel
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-sentinel/issues
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.14
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.15 INFO  ==> ** Starting Redis sentinel setup **
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.18 INFO  ==> Initializing Redis Sentinel...
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.18 INFO  ==> Configuring Redis Sentinel...
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.25 INFO  ==> ** Redis sentinel setup finished! **
container-registry-redis-sentinel-1  |
container-registry-redis-sentinel-1  | redis-sentinel 07:55:08.27 INFO  ==> ** Starting Redis Sentinel **
container-registry-redis-sentinel-1  |
container-registry-redis-sentinel-1  | *** FATAL CONFIG FILE ERROR (Redis 7.0.0) ***
container-registry-redis-sentinel-1  | Reading the configuration file, at line 340
container-registry-redis-sentinel-1  | >>> 'SENTINEL master-reboot-down-after-period mymaster 0'
container-registry-redis-sentinel-1  | No such master with specified name.
```

You can see in the line `SENTINEL master-reboot-down-after-period mymaster 0'` that `mymaster` was not replaced properly in `sentinel.conf`.

Going into the container and checking for `some-other-master` is replaced correctly

```sh
$ cat /bitnami/redis-sentinel/conf/sentinel.conf | grep some-other-master
sentinel monitor some-other-master redis 6379 2
sentinel down-after-milliseconds some-other-master 60000
sentinel parallel-syncs some-other-master 1
sentinel failover-timeout some-other-master 180000
```

But it's not the case for `master-reboot-down-after-period`

```
$ cat /bitnami/redis-sentinel/conf/sentinel.conf | grep mymaster
# sentinel auth-pass mymaster MySUPER--secret-0123passw0rd
# sentinel notification-script mymaster /var/redis/notify.sh
# sentinel client-reconfig-script mymaster /var/redis/reconfig.sh
# instead of the normal ones. For example if the master "mymaster", and the
# SENTINEL rename-command mymaster CONFIG GUESSME
# SENTINEL rename-command mymaster CONFIG CONFIG
SENTINEL master-reboot-down-after-period mymaster 0
```
